function remoteMcpPreset({ id, name, category, url, transport = "http", description, docsUrl = url, auth = "oauth" }) {
  return {
    id,
    name,
    category,
    transport,
    stage: "In alpha, PoC stage",
    docsUrl,
    description: description || `Connect ${name} MCP through its remote ${transport === "sse" ? "SSE" : "Streamable HTTP"} endpoint.`,
    setup: {
      url,
      docsUrl,
      oauth: auth === "oauth" ? { enabled: true, provider: id } : undefined,
      headers: {},
      safety: {
        requireConfirmationForWrites: true,
      },
    },
    instructions: [
      `Use the ${name} MCP endpoint: ${url}.`,
      "Complete provider authentication before discovery if required by the MCP server.",
      "Review scopes, workspace/account access, and write tools before using this connector.",
      "Treat this connector as alpha/PoC until provider-specific OAuth and tool execution flows are hardened.",
    ],
  };
}

const REMOTE_MCP_PRESETS = [
  remoteMcpPreset({ id: "amplitude", name: "Amplitude", category: "Analytics", url: "https://mcp.amplitude.com/mcp", description: "Connect Amplitude MCP for product analytics, cohorts, events, charts, and experimentation workflows." }),
  remoteMcpPreset({ id: "apify", name: "Apify", category: "Automation", url: "https://mcp.apify.com", description: "Connect Apify MCP for actors, web automation, scraping, datasets, and browser workflows." }),
  remoteMcpPreset({ id: "asana", name: "Asana", category: "Productivity", url: "https://mcp.asana.com/mcp", description: "Connect Asana MCP for projects, tasks, goals, portfolios, and team work management." }),
  remoteMcpPreset({ id: "ashby", name: "Ashby", category: "Recruiting", url: "https://mcp.ashbyhq.com/mcp/v1", description: "Connect Ashby MCP for recruiting, candidates, jobs, interviews, and hiring workflows." }),
  remoteMcpPreset({ id: "astro-docs", name: "Astro Docs", category: "Developer docs", url: "https://mcp.docs.astro.build/mcp", description: "Connect Astro Docs MCP for grounded Astro framework documentation lookup." }),
  remoteMcpPreset({ id: "atlassian", name: "Atlassian", category: "Productivity", url: "https://mcp.atlassian.com/v1/sse", transport: "sse", description: "Connect Atlassian MCP for Jira, Confluence, issues, spaces, pages, and team workflows." }),
  remoteMcpPreset({ id: "attio", name: "Attio", category: "CRM", url: "https://mcp.attio.com/mcp", description: "Connect Attio MCP for CRM records, companies, people, lists, notes, and sales workflows." }),
  remoteMcpPreset({ id: "braintrust", name: "Braintrust", category: "AI evaluation", url: "https://api.braintrust.dev/mcp", description: "Connect Braintrust MCP for evals, traces, prompts, experiments, and AI observability." }),
  remoteMcpPreset({ id: "browser-use", name: "Browser Use", category: "Web automation", url: "https://api.browser-use.com/mcp", description: "Connect Browser Use MCP for browser agents, web task execution, and page automation." }),
  remoteMcpPreset({ id: "buildkite", name: "Buildkite", category: "Developer tools", url: "https://mcp.buildkite.com/mcp", description: "Connect Buildkite MCP for pipelines, builds, jobs, agents, and CI/CD workflows." }),
  remoteMcpPreset({ id: "canva", name: "Canva", category: "Design", url: "https://mcp.canva.com/mcp", description: "Connect Canva MCP for designs, assets, brand content, and creative workflows." }),
  remoteMcpPreset({ id: "close", name: "Close CRM", category: "CRM", url: "https://mcp.close.com/mcp", description: "Connect Close MCP for leads, contacts, opportunities, calls, and sales workflows." }),
  remoteMcpPreset({ id: "coda", name: "Coda", category: "Productivity", url: "https://coda.io/apis/mcp", description: "Connect Coda MCP for docs, tables, rows, formulas, and team operating systems." }),
  remoteMcpPreset({ id: "cloudflare-bindings", name: "Cloudflare Bindings", category: "Developer tools", url: "https://bindings.mcp.cloudflare.com/sse", transport: "sse", description: "Connect Cloudflare Bindings MCP for Cloudflare developer resources and bindings workflows." }),
  remoteMcpPreset({ id: "cloudinary-assets", name: "Cloudinary Asset Management", category: "Media", url: "https://asset-management.mcp.cloudinary.com/sse", transport: "sse", description: "Connect Cloudinary MCP for asset management, media library, transformations, and delivery workflows." }),
  remoteMcpPreset({ id: "context7", name: "Context7", category: "Developer docs", url: "https://mcp.context7.com/mcp", description: "Connect Context7 MCP for current library documentation and code-grounded answers." }),
  remoteMcpPreset({ id: "debitura", name: "Debitura", category: "Finance", url: "https://mcp.debitura.com/mcp", description: "Connect Debitura MCP for debt collection and receivables workflows." }),
  remoteMcpPreset({ id: "deepwiki", name: "DeepWiki", category: "Knowledge", url: "https://mcp.deepwiki.com/mcp", description: "Connect DeepWiki MCP for repository and documentation knowledge retrieval." }),
  remoteMcpPreset({ id: "demodesk", name: "Demodesk", category: "Sales", url: "https://demodesk.com/mcp", description: "Connect Demodesk MCP for meetings, demos, scheduling, and sales engagement workflows." }),
  remoteMcpPreset({ id: "fireflies", name: "Fireflies.ai", category: "Meetings", url: "https://api.fireflies.ai/mcp", description: "Connect Fireflies MCP for meeting transcripts, notes, summaries, and conversation intelligence." }),
  remoteMcpPreset({ id: "github-copilot", name: "GitHub Copilot", category: "Developer tools", url: "https://api.githubcopilot.com/mcp/", description: "Connect GitHub Copilot MCP for coding assistant and repository-aware developer workflows." }),
  remoteMcpPreset({ id: "honeycomb", name: "Honeycomb", category: "Observability", url: "https://mcp.honeycomb.io/mcp", description: "Connect Honeycomb MCP for telemetry, traces, datasets, queries, and observability workflows." }),
  remoteMcpPreset({ id: "hugging-face", name: "Hugging Face", category: "AI platform", url: "https://hf.co/mcp", description: "Connect Hugging Face MCP for models, datasets, Spaces, and AI platform workflows." }),
  remoteMcpPreset({ id: "instantdb", name: "InstantDB", category: "Databases", url: "https://mcp.instantdb.com/mcp", description: "Connect InstantDB MCP for app database, schema, query, and data workflows." }),
  remoteMcpPreset({ id: "intercom", name: "Intercom", category: "Support", url: "https://mcp.intercom.com/sse", transport: "sse", description: "Connect Intercom MCP for conversations, contacts, tickets, articles, and support workflows." }),
  remoteMcpPreset({ id: "jamie", name: "Jamie", category: "Meetings", url: "https://mcp.meetjamie.ai/mcp", description: "Connect Jamie MCP for meeting notes, summaries, transcripts, and follow-up workflows." }),
  remoteMcpPreset({ id: "lawbster", name: "Lawbster", category: "Legal", url: "https://lawbster.planitprima.com/mcp", description: "Connect Lawbster MCP for legal workflow and knowledge tasks." }),
  remoteMcpPreset({ id: "lazyweb", name: "Lazyweb", category: "Web", url: "https://www.lazyweb.com/mcp", description: "Connect Lazyweb MCP for web research and browsing workflows." }),
  remoteMcpPreset({ id: "linear", name: "Linear", category: "Productivity", url: "https://mcp.linear.app/sse", transport: "sse", description: "Connect Linear MCP for issues, projects, cycles, teams, and product development workflows." }),
  remoteMcpPreset({ id: "microsoft-learn", name: "Microsoft Learn", category: "Developer docs", url: "https://learn.microsoft.com/api/mcp", description: "Connect Microsoft Learn MCP for Microsoft documentation-grounded answers." }),
  remoteMcpPreset({ id: "mobbin", name: "Mobbin", category: "Design", url: "https://api.mobbin.com/mcp", description: "Connect Mobbin MCP for product design patterns, screenshots, and UI research." }),
  remoteMcpPreset({ id: "modjo", name: "Modjo", category: "Sales", url: "https://api.mcp.modjo.ai/v1/mcp", description: "Connect Modjo MCP for sales calls, conversation intelligence, coaching, and CRM workflows." }),
  remoteMcpPreset({ id: "neon", name: "Neon", category: "Databases", url: "https://mcp.neon.tech/mcp", description: "Connect Neon MCP for Postgres projects, branches, databases, and developer workflows." }),
  remoteMcpPreset({ id: "netlify", name: "Netlify", category: "Developer tools", url: "https://netlify-mcp.netlify.app/mcp", description: "Connect Netlify MCP for sites, deploys, builds, logs, and hosting workflows." }),
  remoteMcpPreset({ id: "pagerduty", name: "PagerDuty", category: "Incident management", url: "https://mcp.pagerduty.com/sse", transport: "sse", description: "Connect PagerDuty MCP for incidents, services, escalation policies, on-call, and response workflows." }),
  remoteMcpPreset({ id: "pipedream", name: "Pipedream", category: "Automation", url: "https://mcp.pipedream.net/YOUR_UUID/YOUR_APP", description: "Connect a Pipedream app MCP endpoint. Replace YOUR_UUID and YOUR_APP with the concrete endpoint from Pipedream." }),
  remoteMcpPreset({ id: "pipedrive", name: "Pipedrive", category: "CRM", url: "https://mcp.pipedrive.ai/mcp", description: "Connect Pipedrive MCP for deals, people, organizations, activities, and sales pipeline workflows." }),
  remoteMcpPreset({ id: "plaid", name: "Plaid", category: "Finance", url: "https://api.dashboard.plaid.com/mcp/sse", transport: "sse", description: "Connect Plaid MCP for financial data, dashboard, apps, accounts, and banking workflows." }),
  remoteMcpPreset({ id: "posthog", name: "PostHog", category: "Analytics", url: "https://mcp.posthog.com/sse", transport: "sse", description: "Connect PostHog MCP for product analytics, feature flags, experiments, events, and insights." }),
  remoteMcpPreset({ id: "postman", name: "Postman", category: "Developer tools", url: "https://mcp.postman.com/minimal", description: "Connect Postman MCP for API collections, requests, workspaces, and API development workflows." }),
  remoteMcpPreset({ id: "prisma", name: "Prisma", category: "Databases", url: "https://mcp.prisma.io/mcp", description: "Connect Prisma MCP for ORM, schema, database, migration, and data workflows." }),
  remoteMcpPreset({ id: "ramp", name: "Ramp", category: "Finance", url: "https://ramp-mcp-remote.ramp.com/mcp", description: "Connect Ramp MCP for expenses, cards, vendors, bills, reimbursements, and finance operations." }),
  remoteMcpPreset({ id: "render", name: "Render", category: "Developer tools", url: "https://mcp.render.com/mcp", description: "Connect Render MCP for services, deploys, logs, environments, and cloud hosting workflows." }),
  remoteMcpPreset({ id: "replicate", name: "Replicate", category: "AI platform", url: "https://mcp.replicate.com/sse", transport: "sse", description: "Connect Replicate MCP for models, predictions, deployments, and AI media workflows." }),
  remoteMcpPreset({ id: "sanity", name: "Sanity", category: "CMS", url: "https://mcp.sanity.io", description: "Connect Sanity MCP for content lake, schemas, documents, and CMS workflows." }),
  remoteMcpPreset({ id: "semgrep", name: "Semgrep", category: "Security", url: "https://mcp.semgrep.ai/mcp", description: "Connect Semgrep MCP for code security findings, rules, scans, and AppSec workflows." }),
  remoteMcpPreset({ id: "sentry", name: "Sentry", category: "Observability", url: "https://mcp.sentry.dev/mcp", description: "Connect Sentry MCP for errors, traces, issues, releases, and application monitoring workflows." }),
];

export const MCP_CATALOG = [
  {
    id: "pinelabs",
    name: "Pine Labs Online Payments",
    category: "Payments",
    transport: "http",
    stage: "In alpha, PoC stage",
    docsUrl: "https://www.pinelabs.com/docs/online-payments/ai/mcp-server",
    description: "Connect Pine Labs Online MCP for payment API exploration, checkout orders, payment links, refunds, and transaction visibility.",
    setup: {
      url: "https://your-pinelabs-mcp-server.example.com/mcp",
      docsUrl: "https://www.pinelabs.com/docs/online-payments/ai/mcp-server",
      headers: {
        Authorization: "Bearer <PINE_LABS_TOKEN>",
      },
      safety: {
        requireConfirmationForTools: ["createOrder", "refund", "create_payment_link"],
        backendOnly: true,
      },
    },
    instructions: [
      "Pine Labs documents the MCP server as Streamable HTTP for compatible AI tools.",
      "Replace the placeholder URL with the endpoint from your Pine Labs MCP setup guide or internal deployment.",
      "Keep payment credentials server-side and confirm order/refund/payment-link actions before tool execution.",
      "Review generated payment code and API calls before production use.",
    ],
  },
  {
    id: "notion",
    name: "Notion",
    category: "Knowledge",
    transport: "http",
    stage: "In alpha, PoC stage",
    docsUrl: "https://developers.notion.com/guides/mcp/overview",
    description: "Search, read, and update Notion workspace content through Notion's hosted MCP server.",
    setup: {
      url: "https://mcp.notion.com/mcp",
      docsUrl: "https://developers.notion.com/guides/mcp/overview",
      oauth: {
        enabled: true,
        provider: "notion",
        pkce: true,
      },
      headers: {},
    },
    instructions: [
      "Use the hosted Notion MCP endpoint: https://mcp.notion.com/mcp.",
      "Complete Notion OAuth before discovery; bearer tokens are not supported for the hosted server.",
      "Use https://mcp.notion.com/sse only as a legacy SSE fallback.",
    ],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Payments",
    transport: "http",
    stage: "In alpha, PoC stage",
    docsUrl: "https://docs.stripe.com/mcp",
    description: "Connect Stripe MCP for payment, billing, customer, and dashboard workflows through Stripe's hosted MCP server.",
    setup: {
      url: "https://mcp.stripe.com",
      docsUrl: "https://docs.stripe.com/mcp",
      oauth: {
        enabled: true,
        provider: "stripe",
      },
      headers: {
        Authorization: "Bearer <OPTIONAL_RESTRICTED_STRIPE_KEY>",
      },
      safety: {
        preferOAuth: true,
        requireConfirmationForTools: ["create_payment", "refund", "create_invoice", "cancel_subscription"],
      },
    },
    instructions: [
      "Stripe recommends OAuth for MCP where the client supports it.",
      "If OAuth is unavailable, use a restricted API key in the Authorization header.",
      "Confirm all payment, refund, invoice, and subscription-changing actions before execution.",
    ],
  },
  {
    id: "paypal",
    name: "PayPal",
    category: "Payments",
    transport: "sse",
    stage: "In alpha, PoC stage",
    docsUrl: "https://mcp.paypal.com/sse",
    description: "Connect PayPal MCP for payment, checkout, order, refund, and account workflows through PayPal's SSE endpoint.",
    setup: {
      url: "https://mcp.paypal.com/sse",
      docsUrl: "https://mcp.paypal.com/sse",
      oauth: {
        enabled: true,
        provider: "paypal",
      },
      headers: {},
      safety: {
        requireConfirmationForTools: ["create_order", "capture_order", "refund", "create_payment", "void_authorization"],
      },
    },
    instructions: [
      "Use the PayPal MCP SSE endpoint: https://mcp.paypal.com/sse.",
      "Complete PayPal authentication before discovery if required by the MCP server.",
      "Confirm buyer, merchant, amount, currency, order, capture, and refund details before executing write actions.",
      "Treat all PayPal money movement tools as high-impact actions during alpha/PoC testing.",
    ],
  },
  {
    id: "clickup",
    name: "ClickUp",
    category: "Productivity",
    transport: "http",
    stage: "In alpha, PoC stage",
    docsUrl: "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
    description: "Connect ClickUp MCP for tasks, docs, comments, time tracking, reports, and workspace search.",
    setup: {
      url: "https://mcp.clickup.com/mcp",
      docsUrl: "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
      oauth: {
        enabled: true,
        provider: "clickup",
        pkce: true,
      },
      headers: {},
      safety: {
        noDeleteToolsExpected: true,
      },
    },
    instructions: [
      "ClickUp MCP is documented as public beta and uses https://mcp.clickup.com/mcp.",
      "Custom clients need OAuth 2.1 with PKCE and may need redirect URI review/allowlisting.",
      "Respect ClickUp workspace rate limits during discovery and chat workflows.",
    ],
  },
  {
    id: "slack-remote",
    name: "Slack Remote",
    category: "Productivity",
    transport: "http",
    stage: "In alpha, PoC stage",
    docsUrl: "https://docs.slack.dev/ai/slack-mcp-server/",
    description: "Connect Slack's hosted MCP server for channel search, messages, files, canvases, users, and collaboration actions.",
    setup: {
      url: "https://mcp.slack.com/mcp",
      docsUrl: "https://docs.slack.dev/ai/slack-mcp-server/",
      oauth: {
        enabled: true,
        provider: "slack",
        clientId: "",
        clientSecret: "",
      },
      headers: {},
      safety: {
        requireConfirmationForTools: ["send_message", "create_conversation", "add_reaction", "create_canvas", "update_canvas"],
      },
    },
    instructions: [
      "Slack supports JSON-RPC over Streamable HTTP at https://mcp.slack.com/mcp.",
      "Slack does not support SSE for this server.",
      "Use a Marketplace-published or internal Slack app with confidential OAuth.",
      "Confirm message, channel, reaction, and canvas write actions before execution.",
    ],
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "Productivity",
    transport: "http",
    stage: "In alpha, PoC stage",
    docsUrl: "https://developers.google.com/workspace/gmail/api/guides/configure-mcp-server",
    description: "Connect Google's Gmail remote MCP server for reading and composing Gmail with OAuth-controlled scopes.",
    setup: {
      url: "https://gmailmcp.googleapis.com/mcp/v1",
      docsUrl: "https://developers.google.com/workspace/gmail/api/guides/configure-mcp-server",
      oauth: {
        enabled: true,
        provider: "google-gmail",
        clientId: "",
        clientSecret: "",
        scopes: ["https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/gmail.compose"],
      },
      headers: {},
      safety: {
        requireConfirmationForTools: ["send_email", "create_draft"],
      },
    },
    instructions: [
      "Enable Gmail API and configure Google Auth Platform before connecting.",
      "Add Gmail readonly and compose scopes for the MCP server.",
      "Create an OAuth web client and add the redirect URI required by your MCP client.",
      "Confirm email send actions before execution.",
    ],
  },
  {
    id: "google-maps",
    name: "Google Maps Grounding Lite",
    category: "Maps",
    transport: "http",
    stage: "In alpha, PoC stage",
    docsUrl: "https://developers.google.com/maps/ai/grounding-lite/reference/mcp",
    description: "Connect Google's Maps Grounding Lite MCP server for place search, weather lookup, route computation, and Google Maps URL/name resolution.",
    setup: {
      url: "https://mapstools.googleapis.com/mcp",
      docsUrl: "https://developers.google.com/maps/ai/grounding-lite/reference/mcp",
      oauth: {
        enabled: true,
        provider: "google-cloud-maps",
        scopes: ["https://www.googleapis.com/auth/cloud-platform"],
      },
      headers: {},
      tools: ["search_places", "lookup_weather", "compute_routes", "resolve_names", "resolve_maps_urls"],
      safety: {
        requireAttribution: true,
        requireSpecificLocationForSearch: true,
      },
    },
    instructions: [
      "Enable Google Cloud MCP servers and set up authentication before use.",
      "Use the global Maps Grounding Lite MCP endpoint: https://mapstools.googleapis.com/mcp.",
      "Available documented tools include search_places, lookup_weather, compute_routes, resolve_names, and resolve_maps_urls.",
      "For place search, include a specific location or location bias to avoid ambiguous queries.",
      "Grounded outputs should preserve Google Maps attribution when returned by the MCP server.",
    ],
  },
  {
    id: "monday",
    name: "Monday.com",
    category: "Productivity",
    transport: "sse",
    stage: "In alpha, PoC stage",
    docsUrl: "https://mcp.monday.com/sse",
    description: "Connect Monday.com MCP for workspace, board, item, update, and project-management workflows through Monday.com's SSE endpoint.",
    setup: {
      url: "https://mcp.monday.com/sse",
      docsUrl: "https://mcp.monday.com/sse",
      oauth: {
        enabled: true,
        provider: "monday",
      },
      headers: {},
      safety: {
        requireConfirmationForTools: ["create_item", "update_item", "delete_item", "create_update", "change_column_value"],
      },
    },
    instructions: [
      "Use the Monday.com MCP SSE endpoint: https://mcp.monday.com/sse.",
      "Complete Monday.com authentication before discovery if required by the MCP server.",
      "Confirm board, item, status, owner, date, and column changes before executing write actions.",
      "Treat project-management writes and deletes as high-impact actions during alpha/PoC testing.",
    ],
  },
  ...REMOTE_MCP_PRESETS,
  {
    id: "hubspot",
    name: "HubSpot CRM",
    category: "CRM",
    transport: "http",
    description: "Read and act on HubSpot CRM records, activities, content, campaigns, and marketing email data through HubSpot's remote MCP server.",
    setup: {
      url: "https://mcp.hubspot.com/",
      oauth: {
        enabled: true,
        provider: "hubspot",
        clientId: "",
        clientSecret: "",
        redirectUrl: "http://localhost:3000/api/mcp/oauth/callback",
      },
      headers: {},
    },
    instructions: [
      "Create an MCP Auth App in HubSpot under Development > MCP Auth Apps.",
      "Add this redirect URL to the HubSpot app: http://localhost:3000/api/mcp/oauth/callback",
      "Paste the HubSpot Client ID and Client Secret into the config JSON.",
      "Save, then click Start OAuth and authorize the HubSpot account.",
      "After OAuth completes, click Discover to list HubSpot tools and verify access.",
    ],
  },
  {
    id: "swiggy-food",
    name: "Swiggy Food",
    category: "Commerce",
    transport: "http",
    description: "Search restaurants, browse menus, manage food carts, place COD food orders, and track delivery through Swiggy's Food MCP server.",
    setup: {
      url: "https://mcp.swiggy.com/food",
      oauth: {
        enabled: true,
        provider: "swiggy",
        redirectUrl: "http://localhost:3000/api/mcp/oauth/callback",
        scope: "mcp:tools mcp:resources mcp:prompts",
      },
      headers: {},
      safety: {
        requireConfirmationForTools: ["place_food_order"],
        cartTotalCapInr: 1000,
        paymentMethod: "COD",
      },
    },
    instructions: [
      "Use localhost for development. Production redirect URLs must be exact HTTPS URLs approved by Swiggy Builders Club.",
      "Add this redirect URL for local development: http://localhost:3000/api/mcp/oauth/callback",
      "Save, click Start OAuth, then complete Swiggy phone + OTP authorization.",
      "Discover tools and start with get_addresses before searching restaurants.",
      "Ordering flow: get_addresses -> search_restaurants -> get_restaurant_menu -> update_food_cart -> get_food_cart -> place_food_order -> track_food_order.",
      "Always confirm cart items and total with the user before place_food_order. Swiggy v1 supports COD and a Rs. 1000 cart cap.",
    ],
  },
  {
    id: "swiggy-instamart",
    name: "Swiggy Instamart",
    category: "Commerce",
    transport: "http",
    description: "Connect Swiggy Instamart MCP for grocery search, cart, and checkout flows.",
    setup: {
      url: "https://mcp.swiggy.com/im",
      oauth: {
        enabled: true,
        provider: "swiggy",
        redirectUrl: "http://localhost:3000/api/mcp/oauth/callback",
        scope: "mcp:tools mcp:resources mcp:prompts",
      },
      headers: {},
      safety: {
        requireConfirmationForTools: ["place_instamart_order", "checkout_instamart_cart"],
      },
    },
    instructions: [
      "Save, click Start OAuth, then complete Swiggy phone + OTP authorization.",
      "Production access requires an approved exact HTTPS redirect URI from Swiggy Builders Club.",
      "Always confirm cart contents, delivery address, and total before checkout or order placement tools.",
    ],
  },
  {
    id: "swiggy-dineout",
    name: "Swiggy Dineout",
    category: "Commerce",
    transport: "http",
    description: "Connect Swiggy Dineout MCP for restaurant discovery, availability, and table reservation flows.",
    setup: {
      url: "https://mcp.swiggy.com/dineout",
      oauth: {
        enabled: true,
        provider: "swiggy",
        redirectUrl: "http://localhost:3000/api/mcp/oauth/callback",
        scope: "mcp:tools mcp:resources mcp:prompts",
      },
      headers: {},
      safety: {
        requireConfirmationForTools: ["book_table", "create_reservation"],
      },
    },
    instructions: [
      "Save, click Start OAuth, then complete Swiggy phone + OTP authorization.",
      "Production access requires an approved exact HTTPS redirect URI from Swiggy Builders Club.",
      "Always confirm restaurant, date, time, party size, and any booking terms before reservation tools.",
    ],
  },
  {
    id: "custom-http",
    name: "Custom HTTP MCP",
    category: "Custom",
    transport: "http",
    description: "Connect any remote Streamable HTTP MCP server.",
    setup: { url: "https://your-server.example.com/mcp", headers: {} },
  },
  {
    id: "custom-sse",
    name: "Custom SSE MCP",
    category: "Custom",
    transport: "sse",
    description: "Connect a legacy HTTP+SSE MCP server.",
    setup: { url: "https://your-server.example.com/sse", headers: {} },
  },
  {
    id: "custom-stdio",
    name: "Custom stdio MCP",
    category: "Custom",
    transport: "stdio",
    description: "Connect a local MCP process using a command and arguments.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-filesystem", "."] },
  },
  {
    id: "filesystem",
    name: "Filesystem",
    category: "Developer tools",
    transport: "stdio",
    description: "Browse and work with allowed local files through the reference filesystem server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-filesystem", "."] },
  },
  {
    id: "github",
    name: "GitHub",
    category: "Developer tools",
    transport: "stdio",
    description: "Repository issues, pull requests, files, and automation through a GitHub MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-github"], env: { GITHUB_PERSONAL_ACCESS_TOKEN: "" } },
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    category: "Databases",
    transport: "stdio",
    description: "Inspect and query PostgreSQL databases from chat.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://user:password@localhost:5432/db"] },
  },
  {
    id: "sqlite",
    name: "SQLite",
    category: "Databases",
    transport: "stdio",
    description: "Explore local SQLite databases with MCP tools and resources.",
    setup: { command: "npx", args: ["-y", "mcp-server-sqlite", "data/app.sqlite"] },
  },
  {
    id: "slack",
    name: "Slack",
    category: "Productivity",
    transport: "stdio",
    description: "Search channels and post messages through a Slack MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-slack"], env: { SLACK_BOT_TOKEN: "", SLACK_TEAM_ID: "" } },
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "Knowledge",
    transport: "stdio",
    description: "Search and retrieve Drive files through an MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-gdrive"], env: { GOOGLE_APPLICATION_CREDENTIALS: "" } },
  },
  {
    id: "brave-search",
    name: "Brave Search",
    category: "Web",
    transport: "stdio",
    description: "Use Brave web search as an MCP tool.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-brave-search"], env: { BRAVE_API_KEY: "" } },
  },
  {
    id: "puppeteer",
    name: "Browser automation",
    category: "Web",
    transport: "stdio",
    description: "Browse, inspect, screenshot, and automate web pages through MCP.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-puppeteer"] },
  },
  {
    id: "memory",
    name: "Memory graph",
    category: "Knowledge",
    transport: "stdio",
    description: "Store and retrieve structured memory through a local MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-memory"] },
  },
];
