export const MCP_CATALOG = [
  {
    id: "custom-http",
    name: "Custom HTTP MCP",
    category: "Custom",
    transport: "http",
    description: "Connect any remote Streamable HTTP MCP server.",
    setup: { url: "https://your-server.example.com/mcp", headers: {} },
  },
  {
    id: "custom-sse",
    name: "Custom SSE MCP",
    category: "Custom",
    transport: "sse",
    description: "Connect a legacy HTTP+SSE MCP server.",
    setup: { url: "https://your-server.example.com/sse", headers: {} },
  },
  {
    id: "custom-stdio",
    name: "Custom stdio MCP",
    category: "Custom",
    transport: "stdio",
    description: "Connect a local MCP process using a command and arguments.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-filesystem", "."] },
  },
  {
    id: "filesystem",
    name: "Filesystem",
    category: "Developer tools",
    transport: "stdio",
    description: "Browse and work with allowed local files through the reference filesystem server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-filesystem", "."] },
  },
  {
    id: "github",
    name: "GitHub",
    category: "Developer tools",
    transport: "stdio",
    description: "Repository issues, pull requests, files, and automation through a GitHub MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-github"], env: { GITHUB_PERSONAL_ACCESS_TOKEN: "" } },
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    category: "Databases",
    transport: "stdio",
    description: "Inspect and query PostgreSQL databases from chat.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://user:password@localhost:5432/db"] },
  },
  {
    id: "sqlite",
    name: "SQLite",
    category: "Databases",
    transport: "stdio",
    description: "Explore local SQLite databases with MCP tools and resources.",
    setup: { command: "npx", args: ["-y", "mcp-server-sqlite", "data/app.sqlite"] },
  },
  {
    id: "slack",
    name: "Slack",
    category: "Productivity",
    transport: "stdio",
    description: "Search channels and post messages through a Slack MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-slack"], env: { SLACK_BOT_TOKEN: "", SLACK_TEAM_ID: "" } },
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "Knowledge",
    transport: "stdio",
    description: "Search and retrieve Drive files through an MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-gdrive"], env: { GOOGLE_APPLICATION_CREDENTIALS: "" } },
  },
  {
    id: "brave-search",
    name: "Brave Search",
    category: "Web",
    transport: "stdio",
    description: "Use Brave web search as an MCP tool.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-brave-search"], env: { BRAVE_API_KEY: "" } },
  },
  {
    id: "puppeteer",
    name: "Browser automation",
    category: "Web",
    transport: "stdio",
    description: "Browse, inspect, screenshot, and automate web pages through MCP.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-puppeteer"] },
  },
  {
    id: "memory",
    name: "Memory graph",
    category: "Knowledge",
    transport: "stdio",
    description: "Store and retrieve structured memory through a local MCP server.",
    setup: { command: "npx", args: ["-y", "@modelcontextprotocol/server-memory"] },
  },
];
